const config = {
  REGION: process.env.REACT_APP_REGION || 'REGION_PLACEHOLDER',
  USER_POOL_ID: process.env.REACT_APP_USER_POOL_ID || 'USER_POOL_ID_PLACEHOLDER',
  USER_POOL_CLIENT_ID: process.env.REACT_APP_USER_POOL_CLIENT_ID || 'USER_POOL_CLIENT_ID_PLACEHOLDER',
  API_GATEWAY_URL: process.env.REACT_APP_API_GATEWAY_URL || 'API_GATEWAY_URL_PLACEHOLDER'
};

export default config;
